### ISSUE TITLE
Possible installation problem

### ISSUE THREAD

**Issue by reinout** [zestsoftware/zest.releaser#108]
When making the 5.0 release (with python 3) I got the following:

    running bdist_wheel
    running build
    running build_py
    installing to build/bdist.linux-x86_64/wheel
    running install
    running install_lib
    copying zest/releaser/longtest.py -> build/bdist.linux-x86_64/wheel/zest/releaser
    copying zest/releaser/hg.py -> build/bdist.linux-x86_64/wheel/zest/releaser
    copying zest/releaser/git.py -> build/bdist.linux-x86_64/wheel/zest/releaser
    copying zest/releaser/baserelease.py -> build/bdist.linux-x86_64/wheel/zest/releaser
    copying zest/releaser/__init__.py -> build/bdist.linux-x86_64/wheel/zest/releaser
    copying zest/releaser/lasttaglog.py -> build/bdist.linux-x86_64/wheel/zest/releaser
    copying zest/releaser/fullrelease.py -> build/bdist.linux-x86_64/wheel/zest/releaser
    copying zest/releaser/pypi.py -> build/bdist.linux-x86_64/wheel/zest/releaser
    copying zest/releaser/release.py -> build/bdist.linux-x86_64/wheel/zest/releaser
    copying zest/releaser/postrelease.py -> build/bdist.linux-x86_64/wheel/zest/releaser
    copying zest/releaser/utils.py -> build/bdist.linux-x86_64/wheel/zest/releaser
    copying zest/releaser/svn.py -> build/bdist.linux-x86_64/wheel/zest/releaser
    copying zest/releaser/preparedocs.py -> build/bdist.linux-x86_64/wheel/zest/releaser
    copying zest/releaser/bzr.py -> build/bdist.linux-x86_64/wheel/zest/releaser
    copying zest/releaser/prerelease.py -> build/bdist.linux-x86_64/wheel/zest/releaser
    copying zest/releaser/lasttagdiff.py -> build/bdist.linux-x86_64/wheel/zest/releaser
    copying zest/releaser/vcs.py -> build/bdist.linux-x86_64/wheel/zest/releaser
    copying zest/releaser/choose.py -> build/bdist.linux-x86_64/wheel/zest/releaser
    copying zest/releaser/tests/functional-with-hooks.txt -> build/bdist.linux-x86_64/wheel/zest/releaser/tests
    copying zest/releaser/tests/functional-svn.txt -> build/bdist.linux-x86_64/wheel/zest/releaser/tests
    copying zest/releaser/tests/functional-mercurial.txt -> build/bdist.linux-x86_64/wheel/zest/releaser/tests
    copying zest/releaser/tests/example.tar -> build/bdist.linux-x86_64/wheel/zest/releaser/tests
    copying zest/releaser/tests/__init__.py -> build/bdist.linux-x86_64/wheel/zest/releaser/tests
    copying zest/releaser/tests/baserelease.txt -> build/bdist.linux-x86_64/wheel/zest/releaser/tests
    copying zest/releaser/tests/pypirc_new.txt -> build/bdist.linux-x86_64/wheel/zest/releaser/tests
    copying zest/releaser/tests/vcs.txt -> build/bdist.linux-x86_64/wheel/zest/releaser/tests
    copying zest/releaser/tests/pypirc_both.txt -> build/bdist.linux-x86_64/wheel/zest/releaser/tests
    copying zest/releaser/tests/functional.py -> build/bdist.linux-x86_64/wheel/zest/releaser/tests
    copying zest/releaser/tests/test_setup.py -> build/bdist.linux-x86_64/wheel/zest/releaser/tests
    copying zest/releaser/tests/pypirc_no_release.txt -> build/bdist.linux-x86_64/wheel/zest/releaser/tests
    copying zest/releaser/tests/git.txt -> build/bdist.linux-x86_64/wheel/zest/releaser/tests
    copying zest/releaser/tests/fullrelease.txt -> build/bdist.linux-x86_64/wheel/zest/releaser/tests
    copying zest/releaser/tests/pypirc_yes_release.txt -> build/bdist.linux-x86_64/wheel/zest/releaser/tests
    copying zest/releaser/tests/functional-git.txt -> build/bdist.linux-x86_64/wheel/zest/releaser/tests
    copying zest/releaser/tests/prerelease.txt -> build/bdist.linux-x86_64/wheel/zest/releaser/tests
    copying zest/releaser/tests/gitsvn.txt -> build/bdist.linux-x86_64/wheel/zest/releaser/tests
    copying zest/releaser/tests/pypirc_old.txt -> build/bdist.linux-x86_64/wheel/zest/releaser/tests
    copying zest/releaser/tests/bzr.txt -> build/bdist.linux-x86_64/wheel/zest/releaser/tests
    copying zest/releaser/tests/choose.txt -> build/bdist.linux-x86_64/wheel/zest/releaser/tests
    copying zest/releaser/tests/preparedocs.txt -> build/bdist.linux-x86_64/wheel/zest/releaser/tests
    copying zest/releaser/tests/functional-bzr.txt -> build/bdist.linux-x86_64/wheel/zest/releaser/tests
    copying zest/releaser/tests/release.txt -> build/bdist.linux-x86_64/wheel/zest/releaser/tests
    copying zest/releaser/tests/pypi.txt -> build/bdist.linux-x86_64/wheel/zest/releaser/tests
    copying zest/releaser/tests/svn.txt -> build/bdist.linux-x86_64/wheel/zest/releaser/tests
    copying zest/releaser/tests/hg.txt -> build/bdist.linux-x86_64/wheel/zest/releaser/tests
    copying zest/releaser/tests/utils.txt -> build/bdist.linux-x86_64/wheel/zest/releaser/tests
    copying zest/releaser/tests/postrelease.txt -> build/bdist.linux-x86_64/wheel/zest/releaser/tests
    running install_egg_info
    Copying zest.releaser.egg-info to build/bdist.linux-x86_64/wheel/zest.releaser-5.0-py3.4.egg-info
    Installing build/bdist.linux-x86_64/wheel/zest.releaser-5.0-py3.4-nspkg.pth
    running install_scripts
    creating build/bdist.linux-x86_64/wheel/zest.releaser-5.0.dist-info/WHEEL
    running upload
    Submitting dist/zest.releaser-5.0.tar.gz to https://pypi.python.org/pypi
    Server response (200): OK
    Submitting /tmp/zest.releaser-5.0-szsv0ov6/gitclone/dist/zest.releaser-5.0-py3-none-any.whl to https://pypi.python.org/pypi
    Server response (200): OK
    warning: no previously-included files found matching '.installed.cfg'
    warning: no previously-included files matching '*.pyc' found anywhere in distribution
    Skipping installation of build/bdist.linux-x86_64/wheel/zest/__init__.py (namespace package)
    There were errors or warnings.
    Package upload may have failed.
    Retry this command? [Yes/no/quit/?]n

So... zest.releaser and/or wheel thought there was a problem. Is it about the namespace package mentioned in the last few lines? I don't know right now. Everything seemed to have uploaded just fine.

**Comment by mauritsvanrees** [comment]
We catch the stderr, which in this case has three lines. They are always printed at the end, because we return the stdout followed by the stderr. stderr contains both errors and warnings.

In this case it starts with two lines that are obviously warnings, about 'no previously included files'. Those warnings are from distutils. (recent pip versions include distlib, where those lines are commented out.) Those two lines should have been printed in magenta (I would say: pinkish).

The third line, about 'Skipping installation' is really also a warning. See the original commit in [setuptools](https://bitbucket.org/pypa/setuptools/commits/1bcf91843616a26069980baef72f7df1090c900c#Lsetuptools/command/install_lib.pyT61) where this was added. No 'warning' string is shown at the beginning. Apparently the logging for setuptools is not setup at that point. Looks like the warning is basically saying: "Okay, you are creating a distribution of a namespace package, which is fine, but I am not going to include that ``__init__.py`` file, so I am warning you about that in case you are doing stuff there that you really should not." Indeed, if you pip install zest.releaser in a virtualenv, and look in the `lib/python2.7/site-packages/zest/` directory, there is no ``__init__.py`` file there. Seems fine to me.

Looks like it is only the bdist_wheel command that gives this feedback.  You can see the same when you do it manually:

```
$ python setup.py bdist_wheel > /dev/null
Skipping installation of build/bdist.macosx-10.10-x86_64/wheel/zest/__init__.py (namespace package)
```

The return code of the command is zero, so nothing is really wrong. If we can capture the return code, that would help.

For now, I can add this to the known warnings in `utils._execute_command` so that we at least print that line as a magenta warning instead of red error.
