### ISSUE TITLE
Zip no more?

### ISSUE THREAD

**Issue by hvelarde** [zestsoftware/zest.releaser#125]
I just upgraded my zest.releaser to latest version and noticed that `.zip` files were replaced by `.tar.gz`.

May I ask the reason for this change?

**Comment by reinout** [comment]
See https://github.com/zestsoftware/zest.releaser/issues/76

Originally zest.releaser forced .zip creation because of a 2.4 bug. That's not relevant anymore, so we don't force .zip. So the setuptools default for your OS is now again used, in your case .tar.gz. 

According to @mauritsvanrees, you can put the following in `setup.cfg` to tell setuptools to also create a .zip.:

    [sdist]
    formats = zip,gztar

So... we stopped using an exception and we're back to default now. Ok?

**Comment by hvelarde** [comment]
thanks! I added the wheel format on my configuration also
