### ISSUE TITLE
Automatically release wheels if the wheel package is there?

### ISSUE THREAD

**Issue by gforcada** [zestsoftware/zest.releaser#129]
I'm not sure if there are good reasons for _NOT_ releasing wheel packages, but as it seems to be the future, wouldn't it make sense that instead of having to add some lines on setup.cfg zest.releaser asks to create and upload them if the wheel package is found?

Basically I'm trying to avoid having to add a setup.cfg on my repos only for that :-)

**Comment by mauritsvanrees** [comment]
See http://zestreleaser.readthedocs.org/en/latest/uploading.html#uploading-wheels which says:

"See http://pythonwheels.com for deciding whether this is a good idea for your package. Briefly, if it is a pure Python 2 or pure Python 3 package: just do it."

If there is a way for zest.releaser to determine that it is guaranteed safe to publish wheels for a project, then it would be fine to do that.

Note that zc.buildout currently cannot handle wheels, so it is useless to upload wheels for example for Plone. But then again: if those wheels are already there and there is a pull request for zc.buildout where you can say "look, a fresh Plone install with wheels takes one minute instead of ten," then that would be nice.

Also note that you can add those lines globally in your `~/.pypirc` if you are sure that all python packages that you release are safe for wheels. You can then switch it off for individual projects.

**Comment by reinout** [comment]
Closing this old issue. If you've got `bdist_wheel` in your `setup.cfg`, we'll release wheels.
Even buildout supports wheels now :-)
