### ISSUE TITLE
Add bumpversion command

### ISSUE THREAD

**Issue by mauritsvanrees** [zestsoftware/zest.releaser#160]
Background is again batch editing zope packages, just like issue #159:
https://mail.zope.org/pipermail/zope-dev/2016-January/047076.html

The idea would be to bump the version and update the changelog without doing the rest of the prerelease part. Important:

- Add an option for increasing the micro or minor or major version, to bump the respective version number part.
- Add an option for *keeping* the development part.

This is for cases where you know the next release needs to be more than a micro version number increase, but you do not want to release just yet. For example, you make a backwards incompatible change, but you are not the person who handles the releases.

Again, we will ask for confirmation: the version we display is a proposal for the user.  With `--no-input` you can accept the default without confirmation.

Examples:

- 1.2.3.dev0 becomes 1.2.3
- 1.2.3 with dev becomes 1.2.3.dev0
- 1.2.3.dev0 with --dev probably stays 1.2.3.dev0
- 1.2.3.dev0 with --minor becomes 1.3.0
- 1.2.3.dev0 with --dev and --minor becomes 1.3.0.dev0
- 1.3.0 with --dev becomes 1.3.0.dev0

Future idea (but maybe easy to add immediately): add options for alpha, beta, rc, final release.  So:

- 1.0.dev0 with --alpha becomes 1.0a1
- 1.0.dev0 with --alpha --dev becomes 1.0a1.dev0
- 1.0a1 with --final becomes 1.0

**Comment by mauritsvanrees** [comment]
@mgedmin Would this help you?

**Comment by reinout** [comment]
If something is 1.3.0 dev, 1.3.0 is not yet released. You're making a some change via an external script (the python 3.2 marker stuff from the mailinglist). Fine, something changed. Why would you want to remove the dev marker for that? And why would you want to turn it into a 1.3.1 (thus skipping the not-yet-released 1.3.0 release)?

I can imagine you have several packages at 1.3.2dev, 1.4.5dev and 1.1dev. You then want those to be turned into 1.3.0dev, 1.5.0dev and 1.1dev (this one stays the same?) if you run it with `--minor`, I guess.

Would that not be more logical?

I suspect a `--major` is also needed?

Reinout

**Comment by mgedmin** [comment]
Here's my usecase:
- I release software version 1.2.3
- the version number in git master is incremented to 1.2.4.dev0 as part of the release process (thank you, zest.releaser, for automating this for me!)
- time passes
- I commit extra refactorings/bugfixes; upcoming version number doesn't need to change
- I commit a new feature and now I want to change the upcoming version number to 1.3.0.dev0
- more time passes
- maybe I commit more bugfixes without updating the version number
- maybe I commit more features -- this time without updating the version number
- maybe I commit a breaking change, which would require me to bump to version 2.0.0.dev0, but only once
- eventually I make a new release -- and I don't need to scan my changelog.rst/git log and see see what kinds of changes (bugfix/feature/breaking) I (or other co-maintainers) made because I was/we were careful and were updating the version number every time.

So, what I'd like are two commands:
- bumpversion --feature => compare the current version with the last release tag in the git repo (assuming they both match MAJOR.MINOR.BUGFIX[.SUFFIX]): if MAJOR.MINOR differ, do nothing; if MAJOR.MINOR are the same, then change the version number to MAJOR.(MINOR+1).0.dev0
- bumpversion --breaking => compare the current version with the last release tag in the git repo; if MAJOR differs, do nothing; if MAJOR is the same, change the version to (MAJOR+1).0.0.dev0

**Comment by mgedmin** [comment]
What you suggest almost works for me (bumpversion --dev --minor/--major), *except* I want the extra check of "have we already increased the minor/major version since the last release?"

I don't want to accidentally skip version numbers, and I don't want to do the check manually, if I'm writing a shell one-liner to loop through all 345 zopefoundation repositories because I'm globally dropping Python 3.2 support.  ;-)

**Comment by mauritsvanrees** [comment]
Removing the dev marker was actually more of an after thought as it would be easy to add: someone may like our way of changing the version and changelog without wanting to use the fullrelease. But it makes sense to just use prerelease of course. And when you want to explicitly add it, postrelease is there.
So on second thought, not changing the dev marker is fine. `bumpversion` can just change the basic version and keep the dev marker if it is there, and keep it out if it is not there. (Possibly pre/post/fullrelease could read minor/major options to influence the version, but let's not for now.)
