### ISSUE TITLE
have bumpversion also be able to bump the dev version

### ISSUE THREAD

**Issue by sean-abbott** [zestsoftware/zest.releaser#167]
If I'm working on a larger package, or a multi-part feature, it would be good to be able to differentiate between pre-release packages via bumpversion.

So, for instance bumpversion --development would yield 0.0.3.dev0-> 0.0.3.dev1

**Comment by mauritsvanrees** [comment]
For such a version bump, no change is needed in `CHANGES.rst`, because that will just say `0.0.3 (unreleased)`.
So only `setup.py` needs a change. In this case I would say: just manually edit it.

Also, with the way we currently do this, the bumpversion script would probably conclude that nothing needs to change, something like this:

```
$ bumpversion --development
Checking version bump for development release.
Last tag: 0.0.2
Current version: 0.0.3.dev0
No version bump needed.
```
