### ISSUE TITLE
zest.releaser does not work with newest twine

### ISSUE THREAD

**Issue by gforcada** [zestsoftware/zest.releaser#183]
Hi,

I've been making some releases lately and before doing that I'm usually doing ``pip install -U pip zest.releaser[recommended]``.

This means that newer versions of twine were being installed (1.7+) and I had to revert them to version 1.6.5 (did not test other releases).

Unfortunately they don't provide a changelog file whatsoever, but after 1.6.5 already comes 1.7 and 1.7.1 and 1.7.2.

The traceback that I get is the following one:

```
There were errors or warnings.
ERROR: Package upload has failed.
Traceback (most recent call last):
  File "/haproxy_log_analysis/lib/python2.7/site-packages/zest/releaser/utils.py", line 749, in retry_twine
    return twine_function(*twine_args)
TypeError: upload() takes exactly 12 arguments (10 given)
```

**Comment by reinout** [comment]
Their changelog is in the docs/ directory: https://github.com/pypa/twine/blob/79e0c8fe1991a6a613ff1ace107b646a6832dd5a/docs/changelog.rst

**Comment by reinout** [comment]
The change that broke us: https://github.com/pypa/twine/commit/ece3711fb7e69891b1ed8f86314a2762dbe64454

We *are* calling a function with 10 parameters (which are now 12). That's not really a proper API function to call. Either we're calling the wrong function or they need to provide a good one or they ought to use keyword arguments.

**Comment by reinout** [comment]
See https://github.com/pypa/twine/issues/194

**Comment by sigmavirus24** [comment]
To summarize the discussion on twine, you *are* calling the wrong function. I've outlined roughly what you need to do to use our semi-public API.

**Comment by grahamar** [comment]
Same with the register command

**Comment by jensens** [comment]
Seems like twine is not really the right tool, overall sounds like its not meant to be used as API. What a shame, it comes in handy.

Anyway, pinning down to twine 1.6.5 and all works for now.

**Comment by sigmavirus24** [comment]
> Seems like twine is not really the right tool, overall sounds like its not meant to be used as API.

@jensens as I explained to @reinout there's an API, it just isn't documented (hence why I referred to it as "semi-public"). I provided an example. If that is still not the right tool, then I'm sorry but I don't understand what you need.

**Comment by mauritsvanrees** [comment]
`twine` is good to use. Options currently:

1. Let `zest.releaser` call `twine` on the command line instead of importing it and calling a function (`upload` or `register`).
2. Change `zest.releaser` to call the function in the way that twine 1.7+ expects, and depend on that minimal version. (Or try the previous call as fallback.)
3. Create a stable public api in `twine`. It might be enough to simply use keyword arguments in the `upload` and `register` function. So either wait for someone to do that, or realise that one of us may have to be that someone. :-) For reference, here is the biggest part of our code that interacts with twine: https://github.com/zestsoftware/zest.releaser/blob/6.6.4/zest/releaser/utils.py#L735

Number 3 would be the nicest, but number 2 is the easiest way forward for now. I just did not take time yet to work on either of them.

**Comment by sigmavirus24** [comment]
So 3 is possible. I'm going to keep the API documented in the Twine issue as it is now until we get around to a 2.0. If one of y'all would like to write actual documentation for Twine's API, that would be great. I'm currently swamped with other tasks.
