### ISSUE TITLE
some questions i couldn't answer myself by reading the docs

### ISSUE THREAD

**Issue by iham** [zestsoftware/zest.releaser#195]
zest.releaser is a great tool for sure and i love automation where ever i can do it ;)
that said and fiddling around with it for the last few days i have some thoughts i want to share:

## version number search/replace on several files. ##
i know i can change the *.py and *.rst where to grab and change the version using:
```
[zest.releaser]
python-file-with-version = my_file_with_version_number.py
history_file = NOT_CHANGES.rst
```
but how can i ADD another file which uses the same versioning pattern and should be changed too?
as a plone developer my packages use GenericSetup and therefore have a my/package/profiles/default/metadata.xml which looks like that:
```
<?xml version="1.0"?>
<metadata>
  <version>1.0</version>
  <dependencies></dependencies>
</metadata>
```
so there is a version tag that should be incremented too.
maybe there would be some other config files (like bower.json, grunt, whatever), or similar files which also need automated version number incrementation. -> **issue or is there a way already?**

## more control over version numbers would be cool ##
having "only" --breaking (why not --major btw?*) and --feature (why not --minor?*) on bumpversion as options doesn't satisfy me - and maybe others aren't too.

(* got it: its because major versions break compatibility and minors implement new features. but still: anywhere i look i see the terms major, minor, patch, etc)

why not use --major (breaking), --minor (feature), --patch (fix), --build (build<n>) --prerelease (a1, b2, ...) to have control over all the possibilities.
 -> **issue or is there a way already?**

## using semver ##
https://pypi.python.org/pypi/semver seems to have the perfect implementation of how to deal with version numbers according to semvers 2.0 -> **issue or is there a way already?**

## relying on version in files only ##
bumpversion relies on git tag. why? -> **issue or is there a way already?**

sry for the long post, but lots of questions popped up during testing/researching/understanding ...

regards,
iham

**Comment by mauritsvanrees** [comment]
Hi Markus, thanks for your questions.

**version number search/replace on several files:**

- Not possible currently, we just change one.  I have no plans on this.
- Obvious problem would be when the two version files have a different number. We could show both and ask the user to pick one.
- In Plone: please only update the `metadata.xml` when your profile has changed and you have a matching upgrade step. This is completely separate from the version in `setup.py`.

**more control over version numbers would be cool:**

- Terminology: there are multiple possible sets of terms, we picked one. The terms are clear, and they fit the sub headings that we have started using in Plone packages, like [here](https://github.com/plone/plonetheme.barceloneta/commit/cb572791a4aefbc2616b1c89509996fd7e35d1b5).
- Three levels seemed enough for a good start. It could be expanded, but I have no plans.

**using semver:**

- Could by nice, but I don't think we gain much. Our code is in [`utils.suggestversion`](https://github.com/zestsoftware/zest.releaser/blob/cdb6c9cd46fe18e8e9fbecd315b3b19aa6814942/zest/releaser/utils.py#L178), which does not look very nice, but we would need to keep most of this anyway in order to know which of the `bump` versions in `semver` we would need to call. Note that this is not only called by `bumpversion`, but also in the pre and post release phase.
- Not all versions that we need to handle are compatible with semver. For example [robot-ride 1.5.2.1](https://pypi.python.org/pypi/robotframework-ride/1.5.2.1). `semver.parse_version_info('1.5.2.1')` gives a ValueError.
- BTW, I have code locally that adjusts our `bumpversion` command to suggest 2.0 instead of 2.0.0, and 1.3 instead of 1.3.0. In the Plone Release Team we have decided we like that more. In a long list of versions it also makes it visually more clear which versions are more than just patch updates. As next development version, my local code always suggests a patch version. I like how it works, but this may need to be configurable in one or two options.

**relying on version in files only:**

- The git (or any vcs) tag is checked to see if a version bump is actually needed. If you are working on version 1.2.3 and you add a new feature, you bump the version to 1.3. If you or someone else adds another feature, but no release has been made yet, then the version should remain at 1.3. In other words, `bumpversion` bumps the version unless it has already been bumped.

**Comment by iham** [comment]
thanks @mauritsvanrees!

you cleared a lot of little blockers in my brains ;)
