### ISSUE TITLE
Abort on PyPi HTTP issues

### ISSUE THREAD

**Issue by miohtama** [zestsoftware/zest.releaser#20]
If PyPi upload fails abort fullrelease

(otherwise reupload attemps become painful when you have done postrelease step)

    Register and upload to pypi (y/N)? yes
    INFO: Running: /Users/mikko/code/plone-venv/bin/python setup.py register -r pypi sdist --formats=zip upload -r pypi
    Showing first few lines...
    running register
    running egg_info
    writing paster_plugins to mfabrik.webandmobile.egg-info/paster_plugins.txt
    writing requirements to mfabrik.webandmobile.egg-info/requires.txt
    writing mfabrik.webandmobile.egg-info/PKG-INFO
    ...
    Showing last few lines...
    unrecognized .svn/entries format in
    Upload failed (503): Server Maintenance

... oops

**Comment by mauritsvanrees** [comment]
If I call `print system(utils.setup_py('My brain hurts'))` currently no error is printed. This is because for python commands we do not show the stderr. See https://github.com/zestsoftware/zest.releaser/blob/3.56/zest/releaser/utils.py#L436
Reason is that this may contain warnings or other fluff that is harmful when we try to extract the version number.
I should probably change a few system calls to quit when there is an error, or to ask the user if she wants to continue.

**Comment by mauritsvanrees** [comment]
I think pull request #90 does this nicely.

**Comment by mauritsvanrees** [comment]
That pull request is merged to master. Will end up in 4.0 soon.
We are not exactly aborting when upload fails, but we print it in red and ask the user if she wants to continue.

**Comment by mgedmin** [comment]
Do you give the user an option to retry?

**Comment by mauritsvanrees** [comment]
No. Would be interesting. I am playing with it now. :-)

**Comment by mgedmin** [comment]
Heh.  I just recently ran fullrelease on a package I didn't have PyPI rights on.  It worked out okay: when the upload failed and zest.releaser asked if I wanted to bump the version to n+1.dev0, I asked for PyPI rights on IRC instead, dug out the temp directory name from xterm scrollback, twine uploaded the sdist, and then let fullrelease continue.
