### ISSUE TITLE
why no egg-release?

### ISSUE THREAD

**Issue by iham** [zestsoftware/zest.releaser#219]
sdist is a normal release methond of zest releaser. (making tar.gz)

why not use eggs too?

make it a options in setup.cfg [zest.releaser]?

**Comment by mauritsvanrees** [comment]
You are the first to ask about this, as far as I remember. Some thoughts:

- Eggs are only useful for packages with C-extensions, and I have never released one of those.
- The newer `wheel` format is arguably better than eggs. (But zc.buildout does not really support wheels yet.)
- For Linux and Mac, eggs are not very useful, because people usually have good C compilers installed there. If you do use them, you could run into problems with 32 vs 64 bit, or the UCS2 vs UCS4 encodings: an egg could run fine on one machine, and be broken on a different one. Wheels have more information in them about on which machines they will run fine.
- On Windows they can be useful. But a developer needs to be be on a Windows machine when building an egg: if you create an egg on Linux or Mac, a Windows user cannot use it. Some projects use special builders for that, which may be hooked up to version control to automatically build and upload an egg when there is a new tag.

It should be doable, but it may be harder than a simple switch in `setup.cfg`. Such an option may need to allow checking if the platform is Windows, or something like that.

It may be better if you or someone else creates an [extension](http://zestreleaser.readthedocs.io/en/latest/entrypoints.html) for `zest.releaser` which hooks in to the [before_upload hook](https://github.com/zestsoftware/zest.releaser/blob/6.10/zest/releaser/release.py#L137).
