### ISSUE TITLE
Hook to autogenerate sphinx docs in prerelease

### ISSUE THREAD

**Issue by MrTango** [zestsoftware/zest.releaser#224]
Is there any chance to have the sphinx docs auto generated before doing the release?

**Comment by reinout** [comment]
Extra pre-release tasks like that is why we have entry points (see http://zestreleaser.readthedocs.io/en/latest/entrypoints.html): you can add extra functionality to zest.releaser.

Something like "generating sphinx docs" is different everywhere: `bin/sphinx`? `make html`? `python -msphinx ...`, etc. So we won't build it in. But with an entry point, you can do it just fine. 

We do something similar ourselves, because we generate a (sphinx...) file with our own entry point:
https://github.com/zestsoftware/zest.releaser/blob/master/zest/releaser/preparedocs.py (look in `setup.py`, where it is configured).

I'm pretty sure someone has already done it. I'm seeing something here: https://github.com/simplesconsultoria/sc.dev.core/blob/e10b8a143a250d077950c606fb80aff68aeb562d/sc/dev/core/sphinx_pypi.py

**Comment by reinout** [comment]
Closing the issue. I assume the answer I gave is enough?
