### ISSUE TITLE
Support version metadata set in setup.cfg

### ISSUE THREAD

**Issue by jensens** [zestsoftware/zest.releaser#241]
If I use an approach where I put as much metadata as possible in ``setup.cfg`` (including version number) I get

    ERROR: We could read a version from setup.py, but could not write it back. 
    See http://zestreleaser.readthedocs.io/en/latest/versions.html for hints.

Would be cool if this will be supported at some point.

Example at https://github.com/collective/pyzanata/blob/master/setup.cfg

**Comment by reinout** [comment]
Ah, the `setup.py` picks it up automatically from the `setup.cfg`. Should be doable with some if/else handling.

Hm. Your `setup.py` sure looks clean and tidy!

**Comment by mauritsvanrees** [comment]
This is in prerelease, right? I do not get this problem when I checkout pyzanata, also not when I try a previous commit. It does not recognise the version though: it suggests 0.0.0.

**Comment by jensens** [comment]
You need a setuptools version supporting it. This is in for a while now. With the version we use in Plone (setuptools 3.1.1) it works already.

**Comment by jensens** [comment]
Err 33.1.1

**Comment by reinout** [comment]
(Looking through old issues :-) )

I think this ought to work now. There's a testcase with a version in `setup.cfg` in our doctest.

And `6.12.4` (from 2017-08-30, which is before your bug report, strangely) already mentions `Also support version in setup.cfg`, which makes me doubt whether your issue is really fixed.
