### ISSUE TITLE
Issue during our dependency-check analysis because of tests/pyproject.toml file

### ISSUE THREAD

**Issue by LvffY** [zestsoftware/zest.releaser#413]
Hello

I have been using your package for a while now and because I love living on the edge, I always used your latest releases. 

Lately, we had an issue with another tool **dependency-check** which pointed some **pyproject.toml** file in your repository : 

![image](https://github.com/zestsoftware/zest.releaser/assets/37327656/7cea3341-cc3b-4f2e-a0e1-74523ca7ab4f)

We solved our problem by enforcing the 7.x releases of your package with **zest.releaser[recommended]<8**.

I'm not sure if this is intended or not, but I'm a bit concerned about the path where this **pyproject.toml** is found. Is this expected that we also install the **tests** directory when installing the library ? *I look into the the library in 7.x, and the <b>tests</b> directory is also included in the library*

N.B: We [could have a workaround](https://github.com/jeremylong/DependencyCheck/issues/5398) by excluding this kind of file of our analysis to use the latest releases of zest.releaser.

**Comment by mauritsvanrees** [comment]
As Plone release manager I maintain hundreds of packages, and when they have a `tests` directory, I include it in the distribution.  This is needed if you want to be able to run the tests for a PyPI distribution instead of a development checkout.  It may be not really needed for `zest.releaser`, but I see nothing wrong with it.

And indeed we do not have a `poetry.lock` or `requirements.txt` in there, and that is fine.
