### ISSUE TITLE
Have a way to update the version in multiple files

### ISSUE THREAD

**Issue by ionelmc** [zestsoftware/zest.releaser#77]
I have a scenario where I'd like:

* to have a single canonical source for the version (release.ini, version.txt or whatever)
* get zest.releaser manage the cannonical location (above mentioned) but also:
  
  * update setup.py with version changes (simple string replace, or some `"version = '(.*)'"` regex)
  * update mypackage/\_\_init\_\_.py with version changes (simple string replace, or some `"__version__ = '(.*)'"` regex)

  Now this would be configurable (you'd give zest.releaser the list of files). 

Essentially that is similar to what https://pypi.python.org/pypi/bumpversion does. 

The advantage is that you don't need to have fragile version loading code anymore in your \_\_init\_\_.py or setup.py.

What do you think?

**Comment by reinout** [comment]
I don't like it, sorry :-) The reason: you *should* have one single canonical source for everything just like you mention. Copying it to various places, even automatically via zest.releaser, isn't the safest/best way to do it.

Have you seen http://zestreleaser.readthedocs.org/en/latest/versions.html#using-the-version-number-in-setup-py-and-as-version ? That's a real easy and quick way to get the right version both in your setup.py and in your application.

**Comment by ionelmc** [comment]
Getting it at runtime isn't safer. My 2 cents.

And I've read that page, a bunch of bad advice, sorry ;-)

**Comment by ionelmc** [comment]
Failures at build/release time are always preferable to failures at runtime (be that be when the package installs or just runs). Fail early in other words. TBH @reinout I expected more than a close with condescending explanation.

**Comment by reinout** [comment]
And in what way is duplicating information safer/better?

Btw, if this functionality you want is something you want in multiple projects: there's nothing stopping you from writing a zest.releaser extension that does exactly what you want. The extension mechanism ("entry points") is there exactly for specific wishes that don't quite match what zest.releaser wants to do for all the other projects out there.

**Comment by reinout** [comment]
Hm. I hear you when you say you were irritated by my 'close' message. Sorry it came across that way.

I confess to being quite irritated at seeing our sound technical reason being labeled "condescending explanation". I point at a solution to your problem that is used by many people all the time. Somehow you find that "brittle". But how can that code possibly fail at runtime? There's no brittleness in there and there'll be no failure. If it were, zest.releaser wouldn't run as it uses the same method :-)

Other methods like reading a `version.txt` are possible, too. How can something like `open('version.txt').read().strip()` at runtime be brittle? If somebody messed up the version string in there or added a couple of lines of text, perhaps? But in that case zest.releaser itself would also stumble over the faulty version string, right? So I would not label that "brittle".

Brittleness is in details like extracting the right version from non-standard locations. You can already point zest.releaser at a non-standard python file, but it requires a quite specific well-formatted version line in that file. It is not very forgiving. It won't understand Django's version tuple (https://github.com/django/django/blob/3f23f1cfb472e77bb1f9260a71b40f895438658d/django/__init__.py#L3) for instance :-) And it very much cannot write it back reliably.

So: I hear your comments, but in my experience they would increase zest.releaser's brittleness and they wouldn't improve the reliability of projects.

But... of course an add-on is possible if you need it in your projects! I could imagine a need to get the version number into some javascript file or `package.json` file.

**Comment by ionelmc** [comment]
I got burnt by all these situations in the past, *they are not theoretical*:

* pkg_resources being broken/missing => runtime failure
* pkg_resources returning wrong version (cause setuptools allows multiple versions installed, crazy) => runtime malfunction
* different current directory, open() tried to use a relative path => installation failure
* getting the version by from the code with exec/import and failing cause assumptions are broken (code tried to import the not-yet-installed dependencies)  => installation failure
* missing data files (like a version.txt) in sdist  => installation failure
* encoding issues, lots of crazy stuff happen when you have non-ascii stuff in files - and you read them (especially on Python 3, which force-feeds you the "unicode sandwich"). 

In light of that, I think it's reasonable to conclude that it's brittle. But I do understand not everyone can get these sorts of problems and I hope you can, in turn, understand there are people who have problems you don't. For example, you don't package for Python 3, but other people do. I suspect you don't have to deal with Windows either.

Can you elaborate a bit on which entrypoints could be pliable to the described goals? Would `zest.releaser.prereleaser.middle` be adequate? In that situation I'd make the version in `setup.py` the "cannonical place" and have the entrypoint update the other places, correct?

If this would be part of zest.releaser how would it make it's codebase more fragile? AFAIK this would be optional behaviour (some flag or argument).

**Comment by reinout** [comment]
Well, every additional optional behaviour makes the code harder to maintain. I recently started using the code I use for finding the readme also for finding a changelog. A nice simplification that also gave some more possibilities.

A few days later I got a bug report because a debian changelog in a subdirectory was found before the actual changelog ('debian' being shorter than the package name...). I had no choice but adding a hardcoded exception. That same code is used for finding a 'version.txt'. Allowing 'version.rst' as an extra option was the reason for using the readme-finding code for the changelog (and the version file).

Similarly, I recently had to remove a fail-safe check that was needed for python 2.4 recently because it interfered with the latest setuptools/pypi changes.

All in all: the current version code is already a quite delicate balance of being generic and supporting many usecases *and* actually working without errors.

"Only optional behaviour" and "just an extra flag": that's very hard to add reliably to a generic piece of code that is used in many projects. I'm maintaining this code for 8 years or so now, so I tend to have a quite good nose for whether things are easy or hard to support reliably.

**But**: I've been wrong before and a pull request is the best way to convince me that something is easy to do :-)

And if it doesn't work out, the code can be copied to an entry point. (Or you can try the entry point first and copy it to a pull request afterwards.)

Regarding entry points, I'd use the 'middle' entry point of the 'prerelease' step. Write out version strings there. Getting the versions right is part of the preparation step before the actual release.

@mauritsvanrees, do you have ideas about this? Perhaps I'm too conservative here.

**Comment by mauritsvanrees** [comment]
I do not see a clear solution here, so that would make me conservative as well. I would happily review a pull request though.

Or it would help to have a pointer to a  package that currently actually fails to install because of this.

Creating a package with an entry point to call bumpversion may be the easiest solution.  The entry point in https://pypi.python.org/pypi/check-manifest may be a nice example.  That package itself would be a solution to the possible 'missing data files' problem you mention.
