### ISSUE TITLE
Slighthly misleading output

### ISSUE THREAD

**Issue by gforcada** [zestsoftware/zest.releaser#98]
When running ``./bin/longtest`` I get the following output:

```
sh: rst2html.py: command not found
INFO: Opening file:///tmp/tmp5dbr1M.html in your webbrowser.
```

Everything works fine, but as longtest first tries to use ``rst2html.py`` which does not exist it shows that error mistakenly leading to users thinking that something went wrong, or that something could/needs to be fixed.

Could it be possible to hide this ``command not found`` and only show it if no rst2html version was found?

**Comment by reinout** [comment]
We could do that. On the other hand, issue #94 probably means we'll use the 'readme' package to check the readme, so that would fix your issue, too: no more external packages would be called.

I'm first going to look at the python3 integration pull request and that's a big one :-)

Thanks for reporting the issue!

**Comment by reinout** [comment]
We now use the 'readme' package, so this issue is solved (on master).
There'll be a 5.0 release soon (with python3 support) that includes the fix.
